[package]
name = "wss-rs"
version = "0.1.0"
edition = "2024"
authors = ["mtb0x1 <mtb0x10x1@gmail.com>"]
description = "A Rust implementation of the wss command"


[dependencies]
clap = { version = "4", features = ["derive"] }
memmap2 = "0.9"